parameters:
    # Name: chilean_way.rut_format
    # Description: Parámetro que indica el formato del RUT que mostrará la aplicación.
    # Options:
    # - 'xxxxxxxxx'    = SIN PUNTOS NI GUION
    # - 'xxxxxxxx-x'   = SIN PUNTOS Y CON GUION
    # - 'xx.xxx.xxx-x' = CON PUNTOS Y GUION
    # Si obtiene cualquier otro formato o valor, se quedará con la opción 'xx.xxx.xxx-x'.
    chilean_way.rut_format: 'xx.xxx.xxx-x'
    # Name: fenec_common.date_format
    # Description: Parámetro que indica el formato de los DATE que son mostrados en la aplicación
    # Options: los formatos disponibles de php para el objeto Date()
    chilean_way.date_format: 'd-m-Y'
    # Name: chilean_way.datetime_format
    # Description: Parámetro que indica el formato de los DATETIME que son mostrados en la aplicación
    # Options: los formatos disponibles de php para el objeto DateTime()
    chilean_way.datetime_format: 'd-m-Y H:i'
    # Name: chilean_way.time_format
    # Description: Parámetro que indica el formato de los TIME que son mostrados en la aplicación
    # Options: los formatos disponibles de php para el objeto Time()
    chilean_way.time_format: 'H:i'
