services:
    # Name: chilean_way_base_twig_extension
    # Description: Par치metro que indica el formato de los TIME que son mostrados en la aplicaci칩n
    # Options: los formatos disponibles de php para el objeto Time()
    chilean_way_twig_extension:
        class: SebaThomson\ChileanWay\Twig\ChileanWayTwigExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    # Name: chilean_way_base_service
    # Description: Par치metro que indica el formato de los TIME que son mostrados en la aplicaci칩n
    # Options: los formatos disponibles de php para el objeto Time()
    chilean_way_service.utils:
        class: SebaThomson\ChileanWay\Services\ChileanWayUtilsService
        arguments: [@service_container]
