services:
    # Name: chilean_way_twig_extension
    # Description: Service for the twig extension
    chilean_way_twig_extension:
        class: SebaThomson\ChileanWay\Twig\ChileanWayTwigExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    # Name: chilean_way_service.utils
    # Description: Service for the utils function
    chilean_way_service.utils:
        class: SebaThomson\ChileanWay\Services\ChileanWayUtilsService
        arguments: [@service_container]
